# Generated by Django 4.1.5 on 2023-02-04 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('Admin_ID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Admin_Name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
                ('Phone_no', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Body',
            fields=[
                ('Body_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_doors', models.IntegerField()),
                ('boot_space', models.IntegerField()),
                ('ground_clearance', models.IntegerField()),
                ('body_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Bought_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Car_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=10)),
                ('Model', models.CharField(max_length=20)),
                ('Mileage', models.FloatField()),
                ('Make', models.CharField(max_length=20)),
                ('kerb_weight', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=25)),
                ('License_No', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Review', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_cylinders', models.IntegerField()),
                ('valves_per_cylinder', models.IntegerField()),
                ('config', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('Engine_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('cc', models.IntegerField()),
                ('fuel_system_type', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddConstraint(
            model_name='cylinder',
            constraint=models.UniqueConstraint(fields=('valves_per_cylinder', 'config'), name='unique_host_migration2'),
        ),
        migrations.AddField(
            model_name='customer_review',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.customer'),
        ),
        migrations.AddField(
            model_name='car',
            name='Admin_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.admin'),
        ),
        migrations.AddField(
            model_name='car',
            name='Engine_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.engine'),
        ),
        migrations.AddField(
            model_name='bought_by',
            name='Car_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car'),
        ),
        migrations.AddField(
            model_name='bought_by',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.customer'),
        ),
        migrations.AddConstraint(
            model_name='customer_review',
            constraint=models.UniqueConstraint(fields=('Customer_ID', 'Customer_Review'), name='unique_host_migration1'),
        ),
    ]
