# Generated by Django 4.1.5 on 2023-01-29 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_ID', models.IntegerField()),
                ('Admin_Name', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('Phone_no', models.CharField(max_length=14)),
            ],
        ),
    ]
