# Generated by Django 4.1.5 on 2023-02-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bought_by',
            constraint=models.UniqueConstraint(fields=('Customer_ID', 'Car_ID'), name='unique_host_migration3'),
        ),
    ]
