# Generated by Django 4.1.5 on 2023-02-06 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_bought_by_unique_host_migration3'),
    ]

    operations = [
        migrations.AddField(
            model_name='body',
            name='Car_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.car'),
        ),
    ]
