# Generated by Django 4.1.5 on 2023-01-29 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0002_remove_admin_admin_id_alter_admin_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Customer_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Customer_Name', models.CharField(max_length=25)),
                ('License_No', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.AddField(
            model_name='admin',
            name='Admin_ID',
            field=models.IntegerField(default=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Customer_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Review', models.CharField(max_length=100)),
                ('Customer_ID1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.customer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='customer_review',
            constraint=models.UniqueConstraint(fields=('Customer_ID1', 'Customer_Review'), name='unique_host_migration'),
        ),
    ]
