# Generated by Django 4.1.5 on 2023-02-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_customer_remove_admin_id_admin_admin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bought_by',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('Car_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('variant', models.CharField(max_length=10)),
                ('Model', models.CharField(max_length=20)),
                ('Mileage', models.FloatField()),
                ('Make', models.CharField(max_length=20)),
                ('kerb_weight', models.IntegerField()),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cylinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_cylinders', models.IntegerField()),
                ('valves_per_cylinder', models.IntegerField()),
                ('config', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('Engine_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('cc', models.IntegerField()),
                ('fuel_system_type', models.CharField(max_length=20)),
                ('capacity', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='customer_review',
            name='unique_host_migration',
        ),
        migrations.RenameField(
            model_name='customer_review',
            old_name='Customer_ID1',
            new_name='Customer_ID',
        ),
        migrations.AddConstraint(
            model_name='customer_review',
            constraint=models.UniqueConstraint(fields=('Customer_ID', 'Customer_Review'), name='unique_host_migration1'),
        ),
        migrations.AddConstraint(
            model_name='cylinder',
            constraint=models.UniqueConstraint(fields=('valves_per_cylinder', 'config'), name='unique_host_migration2'),
        ),
        migrations.AddField(
            model_name='car',
            name='Admin_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.admin'),
        ),
        migrations.AddField(
            model_name='car',
            name='Engine_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='car_app.engine'),
        ),
        migrations.AddField(
            model_name='bought_by',
            name='Car_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.car'),
        ),
        migrations.AddField(
            model_name='bought_by',
            name='Customer_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_app.customer'),
        ),
    ]
