# Generated by Django 4.1.5 on 2023-02-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0003_body_car_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_Review',
        ),
    ]
