# Generated by Django 4.1.5 on 2023-02-06 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0004_delete_customer_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='Admin_Name',
        ),
    ]
